{% set name = "PyPrind" %}
{% set version = "2.11.2" %}
{% set sha256 = "c46cab453b805852853dfe29fd933aa88a2a516153909c695b098e9161a9e675" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1005
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
  run:
    - python
    - psutil >=3.2.0

test:
  imports:
    - pyprind

about:
  home: https://github.com/rasbt/pyprind
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A progress bar and a percentage indicator object that let you track the progress of an iterative computation'
  description: |
    The PyPrind (Python Progress Indicator) module provides a progress bar
    and a percentage indicator object that let you track the progress of a
    loop structure or other iterative computation.
  doc_url: http://pythonhosted.org/PyPrind/
  dev_url: https://github.com/rasbt/pyprind

extra:
  recipe-maintainers:
    - cmutel
