appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QRf7t+SfzGgzFcEHYJhTY76nlUMITpZ+WlhmO/0dL/rgk2Q26JUGiGr78zU8HyMdXQ6REgZlF7aUYT3uvYozS/HTZoCugcy9tGeC3cllRAN54IFMMbPE09jiq3RqR6xEZNAbC4alcaA1FvtrGMoygO7DSf1vLpJ/qcvjsDXipRXmTLZHpTbQorqzBz+8kdwAbCpFzbEJ8AgxWjhZwGjJvh2PiEheJ+yXi+Bv9B3d0yxo80MUNCdy0H5k4hlHqJwSzsUqZQOPIbSRvBf5Mnbi6Ro67FU1hStxNIsle/RasCznGgHxdmQTNRMy3K/iJnc9G7O1f76Z9JyOWb923c1I+VpErowkg7RWNzw0enCQmTfQOkwXYZ3NanENj4EJjRUk4XahE3bMyeLxuVwoShhEzbvmyLdb9MXbngqW3HQSfQMeGXoUy/T47pg9+SbVgcbD5WriVXwqEvJAwTg7Xp+s0K/L/eurbKMigzTpv9Ne/ThfO3QCKs4ByKk8gtFYFqVKLHUvNqqmbmWsnTGzSyYtGavsbFempgBHnTW1r7z4VftmrwKL8hcSkauhT7m0H5IL73VKbt0XN7R5+5t6al8S2jn2V16+0GsxnvG6jyuxrqalQGGPCMlwt8pAkDmcGOUGtI11EipQwBgNgQfo7oXi3NzFLpHF62sJovg18R8jQuE=}
